<?php

/**
 * BaseDpCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $dp_id
 * @property integer $category_id
 * @property Dp $Dp
 * @property Category $Category
 * 
 * @method integer    getDpId()        Returns the current record's "dp_id" value
 * @method integer    getCategoryId()  Returns the current record's "category_id" value
 * @method Dp         getDp()          Returns the current record's "Dp" value
 * @method Category   getCategory()    Returns the current record's "Category" value
 * @method DpCategory setDpId()        Sets the current record's "dp_id" value
 * @method DpCategory setCategoryId()  Sets the current record's "category_id" value
 * @method DpCategory setDp()          Sets the current record's "Dp" value
 * @method DpCategory setCategory()    Sets the current record's "Category" value
 * 
 * @package    dp-navigator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseDpCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dp_category');
        $this->hasColumn('dp_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('category_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dp', array(
             'local' => 'dp_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Category', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}