<?php

/**
 * BaseDpRelation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $source_id
 * @property integer $target_id
 * @property integer $type_id
 * @property Dp $Source
 * @property Dp $Target
 * @property RelationType $Type
 * 
 * @method integer      getSourceId()  Returns the current record's "source_id" value
 * @method integer      getTargetId()  Returns the current record's "target_id" value
 * @method integer      getTypeId()    Returns the current record's "type_id" value
 * @method Dp           getSource()    Returns the current record's "Source" value
 * @method Dp           getTarget()    Returns the current record's "Target" value
 * @method RelationType getType()      Returns the current record's "Type" value
 * @method DpRelation   setSourceId()  Sets the current record's "source_id" value
 * @method DpRelation   setTargetId()  Sets the current record's "target_id" value
 * @method DpRelation   setTypeId()    Sets the current record's "type_id" value
 * @method DpRelation   setSource()    Sets the current record's "Source" value
 * @method DpRelation   setTarget()    Sets the current record's "Target" value
 * @method DpRelation   setType()      Sets the current record's "Type" value
 * 
 * @package    dp-navigator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseDpRelation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('dp_relation');
        $this->hasColumn('source_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('target_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('type_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Dp as Source', array(
             'local' => 'source_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Dp as Target', array(
             'local' => 'target_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('RelationType as Type', array(
             'local' => 'type_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}