<?php

/**
 * BaseRelationType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $DpRelation
 * 
 * @method string              getName()       Returns the current record's "name" value
 * @method Doctrine_Collection getDpRelation() Returns the current record's "DpRelation" collection
 * @method RelationType        setName()       Sets the current record's "name" value
 * @method RelationType        setDpRelation() Sets the current record's "DpRelation" collection
 * 
 * @package    dp-navigator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7021 2010-01-12 20:39:49Z lsmith $
 */
abstract class BaseRelationType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('relation_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DpRelation', array(
             'local' => 'id',
             'foreign' => 'type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}