<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Dps
 * 
 * @method string              getName() Returns the current record's "name" value
 * @method Doctrine_Collection getDps()  Returns the current record's "Dps" collection
 * @method Category            setName() Sets the current record's "name" value
 * @method Category            setDps()  Sets the current record's "Dps" collection
 * 
 * @package    dp-navigator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 600, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '600',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Dp as Dps', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}