# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  website_name: DpNavigator
  pattern_language_presentation: This pattern language is about... #Presentation of your pattern language appearing on different pages.