<?php

/**
 * Dp
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    dp-navigator
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Dp extends BaseDp
{
  /* Manage the string to make appear links */
  public static function pretty($string) {
    //Replace structures as such [[http://google.com]] by <a href="google.com">google.com</a>
	$out = preg_replace('#(\[\[\ *(http://.*?)\ *\]\])#i', '<a href="$2" target="_blank">$2</a>', $string);


	/* The following structure is related to Serious Game's domain.
	   Make this structure more generic in next versions.*/

	//Replace structures like [[758-Americas-Army]] by <a href="http://serious.gameclassification.com/EN/games/758-Americas-Army/index.html">Americas Army</a>
	$out = preg_replace('#(\[\[\ *(\d*-(.*?))\ *\]\])#i', '<a href="http://serious.gameclassification.com/EN/games/$2/index.html" target="_blank">$3</a>', $out);

    //Replace structures as such [[patternname]] by <span class="patternName">patternname</span>
	$out = preg_replace('#(\[\[\ *(.*?)\ *\]\])#i', '<span class="patternName">$2</span>', $out);

	// Transform break line into <br/>
	$out = nl2br($out);

	return $out;
  }
}